version: '3.8'

networks:
  academynet:
    driver: bridge

services:
  mysqldb:
    container_name: db_container
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: student_management
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3407:3306"
    expose:
      - 3306
    networks:
      - academynet
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -P 3306 -u root -p123 | grep 'mysqld is alive' || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5

  app:
    container_name: app_container
    depends_on:
      mysqldb:
          condition: service_healthy
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports: 
      - "3002:3002"
    expose:
      - 3002
    links:
      - "mysqldb:db"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: student_management
      DB_PORT: 3306
      SERVER_PORT: 3000
    networks:
      - academynet
    stdin_open: true
    tty: true
  