version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE='student_management'
      - MYSQL_ALLOW_EMPTY_PASSWORD='ok'
      - MYSQL_ROOT_PASSWORD='123'
      - MYSQL_USER='dbuser'
      - MYSQL_PASSWORD='dbuser'
      - MYSQL_ROOT_HOST='%'
    ports:
      - 3307:3306
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports: 
      - "3000:3000"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=student_management
      - DB_PORT=3306
    stdin_open: true
    tty: true
  